export {default as App} from './App'
export {default as About} from './About'
export {default as Projects} from './Projects'
export {default as Home} from './Home'
export {default as Header} from './Header'